/**
 * Red-Line Contract Comparison Exporter Engine
 * Converts contract diffs into formatted Word-compatible .doc / .html redline documents with tracked additions and strike-through deletions.
 */

export interface ContractDiffItem {
  clauseCategory: string;
  docAText: string;
  docBText: string;
  analysis: string;
  winner?: string;
}

export function generateRedlineDocumentHtml(
  titleA: string,
  titleB: string,
  diffs: ContractDiffItem[]
): string {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const diffRows = diffs
    .map(
      (d, i) => `
    <div style="margin-bottom: 24px; padding: 16px; border: 1px solid #E2E8F0; border-radius: 8px; font-family: 'Times New Roman', serif;">
      <h3 style="font-size: 14pt; color: #0F172A; margin-top: 0; margin-bottom: 8px; border-bottom: 1px solid #CBD5E1; padding-bottom: 4px;">
        Clause ${i + 1}: ${d.clauseCategory}
      </h3>
      
      <div style="margin-bottom: 12px; font-size: 11pt; line-height: 1.6;">
        <strong style="color: #991B1B;">Original (${titleA}):</strong><br/>
        <span style="background-color: #FEE2E2; text-decoration: line-through; color: #7F1D1D; padding: 2px 4px; border-radius: 3px;">
          "${d.docAText || "None"}"
        </span>
      </div>

      <div style="margin-bottom: 12px; font-size: 11pt; line-height: 1.6;">
        <strong style="color: #065F46;">Redline Revision (${titleB}):</strong><br/>
        <span style="background-color: #D1FAE5; color: #064E3B; font-weight: bold; padding: 2px 4px; border-radius: 3px;">
          "${d.docBText || "None"}"
        </span>
      </div>

      <div style="font-size: 10pt; background-color: #F8FAFC; padding: 8px; border-left: 4px solid #1E3A8A; color: #1E293B;">
        <strong>Legal Risk Audit:</strong> ${d.analysis}
      </div>
    </div>
  `
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Contract Redline Markup Report</title>
  <style>
    body { font-family: 'Times New Roman', serif; padding: 40px; color: #0F172A; line-height: 1.6; }
    h1 { font-size: 18pt; color: #1E3A8A; text-align: center; margin-bottom: 4px; }
    .subtitle { text-align: center; font-size: 10pt; color: #64748B; margin-bottom: 32px; }
  </style>
</head>
<body>
  <h1>LAWPILOT AI CONTRACT REDLINE MARKUP</h1>
  <div class="subtitle">Comparison: ${titleA} vs. ${titleB} • Generated: ${dateStr}</div>
  <hr style="border: 0; border-top: 2px solid #1E3A8A; margin-bottom: 24px;" />
  ${diffRows}
  <div style="margin-top: 40px; text-align: center; font-size: 9pt; color: #94A3B8; border-top: 1px solid #E2E8F0; padding-top: 16px;">
    Pre-Audited Enterprise Record • Generated by LawPilot AI Redline Engine
  </div>
</body>
</html>`;
}
